{% set name = "vaex-hdf5" %}
{% set version = "0.7.0" %}
{% set sha256 = "73f898f9bc3fa5c61a67fb31a85be296bbd37d157cdf2a1d48d22f0ccad024c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - vaex-core >=4.0.0,<5
    - h5py >=2.9

test:
  imports:
    - vaex.hdf5

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: hdf5 file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
