{% set name = "vaex-hdf5" %}
{% set version = "0.3.0" %}
{% set sha256 = "4d7b9bf61b821141d13a7f17b98a4b6cc2dbeaeab7dbcd4bd7c613ee750c29e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=0.1
    - h5py

test:
  imports:
    - vaex.hdf5

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: hdf5 file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
